import Footer from "@/components/Footer";
import Navebar from "@/components/Navbar";

import "@/styles/globals.css";
import { AnimatePresence } from "framer-motion";
import { Noto_Kufi_Arabic } from "next/font/google";
import Head from "next/head";
import { useRouter } from "next/router";

const montserrat = Noto_Kufi_Arabic({
  subsets: ["arabic"],
  variable: "--font-inter",
});
export default function App({ Component, pageProps }) {
  const router = useRouter();
  return (
    <>
      <Head>
        <title>ألاقي</title>
        <meta name="description" content="Generated by Alaqy team" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main
        style={{ fontFamily: "Noto Kufi Arabic" }}
        className={`${montserrat.variable} --font-inter bg-light dark:bg-dark w-full min-h-screen `}
      >
        <Navebar />
        <AnimatePresence mode="wait">
          <Component key={router.asPath} {...pageProps} />
        </AnimatePresence>
        <Footer />
      </main>
    </>
  );
}
